name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: write       # Needed for updating badges
  checks: write        # Needed for test reporting

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh {0}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      shell: bash
      run: |
        brew install zsh
        # Make zsh the default shell for the workflow
        sudo chsh -s $(brew --prefix)/bin/zsh $(whoami)
        # Ensure we're running in zsh
        exec zsh
    
    - name: Set up test environment
      run: |
        # Create test directories if they don't exist
        for dir in unit integration system; do
          [[ -d "tests/$dir" ]] || mkdir -p "tests/$dir"
        done
        
        # Make test files executable if they exist
        for test_file in tests/run_tests.sh tests/{unit,integration,system}/*_test.sh; do
          [[ -f "$test_file" ]] && chmod +x "$test_file"
        done
        
        # Create mock home directory structure
        mkdir -p "$HOME/.oh-my-zsh/custom/themes"
        touch "$HOME/.zshrc"
        
        # Set up test environment variables
        echo "TEST_MODE=true" >> $GITHUB_ENV
        echo "RUNNING_TESTS=true" >> $GITHUB_ENV
    
    - name: Run tests
      run: |
        # Run the test suite with error handling
        if ! ./tests/run_tests.sh; then
          echo "::error::Tests failed"
          exit 1
        fi