name: Test and Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up test environment
      run: |
        chmod +x tests/run_tests.sh
        chmod +x tests/unit/setup_functions_test.sh
        chmod +x tests/integration/setup_integration_test.sh
        chmod +x tests/system/setup_system_test.sh
    
    - name: Run tests
      run: |
        ./tests/run_tests.sh
        
    - name: Update test status badge
      if: success()
      run: |
        sed -i '' '/!\[Tests\]/d' README.md
        sed -i '' '/<div align="center">/a\'$'\n''[![Tests](https://github.com/${{ github.repository }}/actions/workflows/test.yml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/test.yml)\'$'\n' README.md
      
    - name: Commit README changes
      if: success() && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: update test status badge [skip ci]"
        
    - name: Push changes
      if: success() && github.event_name == 'push'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 